spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://studmysql01.fhict.local:3306/dbi500882
spring.datasource.username=dbi500882
spring.datasource.password=Dd12345678
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

